### PR TITLE
Add docs for drop/control spans volume

### PR DESCRIPTION
**Pull request by srikanthccv**
Fixes https://github.com/SigNoz/engineering-pod/issues/1272

### CODE REVIEW

**Comment by srikanthccv** [comment]
@Calm-Rock another one

**Comment by Calm-Rock** [comment]
@srikanthccv would it make sense to put this doc under a guides folder for traces management and add it to Tutorials section of APM & Distributed Tracing in the SideNav ?

Something like `traces-management/guides/drop-spans`

**Comment by srikanthccv** [comment]
If that seems like the best place to organize this, I am fine with it.

**Review by Calm-Rock — APPROVED** [review]

**Comment by pranay01** [comment]
@Calm-Rock When I open this page https://signoz.io/docs/traces-management/guides/drop-spans/  - no tab in the side bar gets highlighted. Is this doc not in any section - How will a user discover it if he is browsing the doc?

**Comment by Calm-Rock** [comment]
@pranay01 this is a known issue - https://github.com/SigNoz/signoz-web/issues/204

Ref Slack thread for this issue - [here](https://signoz-team.slack.com/archives/C02BEBF6KM2/p1717673319562859)

You can find this section using this flow in SideNav --> **APM & Distributed Tracing -> Tutorials -> Control Traces Volume**

**Pull request merged**
