### PR TITLE
feat: update pagination design

### PR DESCRIPTION
**Pull request by harshbutfairx**
# before
image

# after
image

### CODE REVIEW

**Comment by GeekBoySupreme** [comment]
The separator between 1 and 9 on the left should be an em-dash `⎯` instead of a hyphen `-`.
Also, all the fonts for numbers here would be ui-monospace.

**Comment by YounixM** [comment]
@harshbutfairx : Please add video recording of the change, with some examples.

**Comment by ankit01-oss** [comment]
> The separator between 1 and 9 on the left should be an em-dash `⎯` instead of a hyphen `-`. Also, all the fonts for numbers here would be ui-monospace.

@harshbutfairx is this taken care of?

**Review by ankit01-oss — APPROVED** [review]

**Comment by harshbutfairx** [comment]
> > The separator between 1 and 9 on the left should be an em-dash `⎯` instead of a hyphen `-`. Also, all the fonts for numbers here would be ui-monospace.
> 
> @harshbutfairx is this taken care of?

@ankit01-oss Yes, the changes have been made.

**Comment by harshbutfairx** [comment]
> @harshbutfairx :build failed. Please check



> @harshbutfairx : Please add video recording of the change, with some examples.

@YounixM 
https://github.com/SigNoz/signoz-web/assets/170525115/17daedbe-7dea-4ebe-8e6e-09612f9219e4

**Pull request merged**
